import type { LucideIcon } from "lucide-react";
import { LayoutDashboard, Settings, Building2, CreditCard, FileText } from "lucide-react";

export interface NavItem {
  title: string;
  href: string;
  icon: LucideIcon;
}

/**
 * Single source of truth for the dashboard sidebar. New dashboard pages
 * (including those generated by the add-dashboard-page skill) register
 * themselves here.
 */
export const navItems: NavItem[] = [
  { title: "Dashboard", href: "/dashboard", icon: LayoutDashboard },
  { title: "Invoices", href: "/dashboard/invoices", icon: FileText },
  { title: "Organization", href: "/dashboard/settings/organization", icon: Building2 },
  { title: "Billing", href: "/dashboard/settings/billing", icon: CreditCard },
  { title: "Settings", href: "/dashboard/settings", icon: Settings },
];
